<!DOCTYPE html>
<html dir="ltr" lang="ja">
  <head>
<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */
wp_head(); // We need this for plugins.
?>

<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
     <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
      <script type="text/javascript" src="<?php echo site_url(); ?>/wp-content/themes/corporate-pro/original/js/jquery.min.js"></script>
    <script src="<?php echo site_url(); ?>/wp-content/themes/corporate-pro/original/js/swiper.js"></script>
    <link type="text/css" rel="stylesheet" href="<?php echo site_url(); ?>/wp-content/themes/corporate-pro/original/css/swiper.css">
    <script type="text/javascript"
src="//code.typesquare.com/static/ZDbTe4IzCko%253D/ts106f.js"
charset="utf-8"></script>
<script src="https://www.postit-web.com/wp-content/themes/wordpress_note/js/jquery.min.js"></script>

<script>
$(function(){
     $(".dropdown1").hide();
     $(".btn-more1").click(function(){
          $(".triger1").prev().slideToggle();
          $(this).toggleClass("close");
     });
});
</script>
<script>
$(function(){
     $(".dropdown2").hide();
     $(".btn-more2").click(function(){
          $(".triger2").prev().slideToggle();
          $(this).toggleClass("close");
     });
});
</script>
<script>
$(function(){
     $(".dropdown3").hide();
     $(".btn-more3").click(function(){
          $(".triger3").prev().slideToggle();
          $(this).toggleClass("close");
     });
});
</script>
<script>
$(function(){
     $(".dropdown4").hide();
     $(".btn-more4").click(function(){
          $(".triger4").prev().slideToggle();
          $(this).toggleClass("close");
     });
});
</script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.0/css/font-awesome.min.css">
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-133215533-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-133215533-1');
</script>
</head>

<body>
    <header class="header">
      <!--pc only-->
      <div class="sp-none">
        <nav>
          <ul class="menu_nav">
            <li class="hover_none p-5">
              <a href="<?php echo esc_url(home_url('/')); ?>">
                  <img src="<?php echo esc_url(home_url()).'/wp/wp-content/uploads/logo.png'; ?>" class="header__logo" alt="アクティブエイジング カイロプラクティック">
              </a>
            </li>

            <li class="menu__none t_c w-auto p-5">
              <a href="<?php echo esc_url(home_url('/about')); ?>"><span class="show-down-md"><i class="fas fa-angle-right"></i></span> <span class="font-b_sp">私たちについて</span></a>
            </li>


            <li class="menu__multi t_c w-auto p-5">
              <a href="#" class="init-bottom">
                <span class="disabled menu__li--exSpan m-l-2">お悩み<span class="show-up-lg"> <i class="fas fa-angle-down" style="margin-left:2px"></i></span></span>
              </a>
              <ul class="menu__second-level">
                <li class="header_small">
                  <a href="<?php echo esc_url(home_url('/parts')); ?>">
                    <span class="show-down-md"><i class="fas fa-angle-right"></i></span>部位別のお悩み
                  </a>
                </li>
                <li class="header_small">
                  <a href="#" class="init-right"><span class="show-down-md"> <i class="fas fa-angle-right"></i></span>専門的なお悩み</a>
                  <ul class="menu__third-level">
                    <li class="header_small">
                      <a href="<?php echo esc_url(home_url('/herniated_disc')); ?>">
                        <span class="show-down-md"><i class="fas fa-angle-right"></i></span>椎間板ヘルニア
                      </a>
                    </li>
                    <li class="header_small">
                      <a href="<?php echo esc_url(home_url('/spinal_canal_stenosis')); ?>">
                        <span class="show-down-md"><i class="fas fa-angle-right"></i></span>脊柱管狭窄症
                      </a>
                    </li>
                    <li class="header_small">
                      <a href="<?php echo esc_url(home_url('/maternity_problems')); ?>">
                        <span class="show-down-md"><i class="fas fa-angle-right"></i></span>産前産後のお悩み
                      </a>
                    </li>
                    <li class="header_small">
                      <a href="<?php echo esc_url(home_url('/deskworker_problems')); ?>">
                        <span class="show-down-md"><i class="fas fa-angle-right"></i></span>デスクワーカーのお悩み
                      </a>
                    </li>
                    <li class="header_small">
                      <a href="<?php echo esc_url(home_url('/sports_injuries')); ?>">
                        <span class="show-down-md"><i class="fas fa-angle-right"></i></span>スポーツ障害
                      </a>
                    </li>
                    <li class="header_small">
                      <a href="<?php echo esc_url(home_url('/osteoarthritis')); ?>">
                        <span class="show-down-md"><i class="fas fa-angle-right"></i></span>変形性膝関節・股関節症
                      </a>
                    </li>
                  </ul>
                </li>
                <li class="header_small">
                  <a href="#" class="init-right"><span class="show-down-md"> <i class="fas fa-angle-right"></i></span>姿勢のお悩み</a>
                  <ul class="menu__third-level">
                    <li class="header_small">
                      <a href="<?php echo esc_url(home_url('/straight_neck')); ?>">
                        <span class="show-down-md"><i class="fas fa-angle-right"></i></span>ストレートネック
                      </a>
                    </li>
                    <li class="header_small">
                      <a href="<?php echo esc_url(home_url('/round_back')); ?>">
                        <span class="show-down-md"><i class="fas fa-angle-right"></i></span>猫背
                      </a>
                    </li>
                    <li class="header_small">
                      <a href="<?php echo esc_url(home_url('/scoliosis')); ?>">
                        <span class="show-down-md"><i class="fas fa-angle-right"></i></span>側わん症
                      </a>
                    </li>
                    <li class="header_small">
                      <a href="<?php echo esc_url(home_url('/straight_back')); ?>">
                        <span class="show-down-md"><i class="fas fa-angle-right"></i></span>ストレートバック
                      </a>
                    </li>
                  </ul>
                </li>
              </ul>
            </li>

            <li class="menu__single t_c w-auto p-5">
              <a href="#" class="init-bottom">施術・サービス<span class="show-up-lg"> <i class="fas fa-angle-down" style="margin-left:2px"></i></span></a>
              <ul class="menu__second-level">
                <li class="header_small">
                  <a href="<?php echo esc_url(home_url('/').'chiropractic'); ?>">
                    <span class="show-down-md"><i class="fas fa-angle-right"></i></span>カイロプラクティック
                  </a>
                </li>
                <li class="header_small">
                  <a href="<?php echo esc_url(home_url('/').'cbp'); ?>">
                    <span class="show-down-md"><i class="fas fa-angle-right"></i></span>CBP®︎姿勢矯正
                  </a>
                </li>
                <li class="header_small">
                  <a href="<?php echo esc_url(home_url('/').'myofascial_release'); ?>">
                    <span class="show-down-md"><i class="fas fa-angle-right"></i></span>筋膜リリース
                  </a>
                </li>
                <li class="header_small">
                  <a href="https://aapilates.jp/"><span class="show-down-md"><i class="fas fa-angle-right"></i></span>ピラティス<span class="font-small">（専門サイトへ）</span>
                  </a>
                </li>
              </ul>
            </li>

            <li class="menu__single m-l t_c w-auto p-5">
              <a href="#" class="init-bottom">当院情報<span class="show-up-lg"> <i class="fas fa-angle-down" style="margin-left:2px"></i></span></span></a>
              <ul class="menu__second-level">
                <li class="header_small p-5">
                  <a href="<?php echo esc_url(home_url('/').'clinic-information/#staff'); ?>"><span class="show-down-md"><i class="fas fa-angle-right"></i></span> スタッフ</a>
                </li>
                <li class="header_small">
                  <a href="https://aachiro.jp/clinic-information/#price"><span class="show-down-md"><i class="fas fa-angle-right"></i></span> 料金</a>
                </li>
                <li class="header_small">
                  <a href="<?php echo esc_url(home_url('/').'clinic-information/#faq'); ?>"><span class="show-down-md"><i class="fas fa-angle-right"></i></span> FAQ</a>
                </li>
                <li class="header_small">
                  <a href="<?php echo esc_url(home_url('/').'clinic-information/#access'); ?>"><span class="show-down-md"><i class="fas fa-angle-right"></i></span> アクセス</a>
                </li>
              </ul>
            </li>

            <li class="t_c pc-en">
              <a href="http://aachiro.tokyo/" class="header__en"><span class="show-down-md"><i class="fas fa-angle-right"></i></span> <span class="font-b_sp">ENGLISH</span></a>
            </li>

            <li class="ml-20">
              <p class="header__contact"><a href="<?php echo site_url(); ?>/contact/"><i class="far fa-envelope"></i> E-MAIL</a></p>
              <p class="header__contact--tel">
              <a href="tel:0363124223">☎03-6312-4223</a>
              </p>
            </li>

          </ul>
        </nav>
      </div><!-- // pc only-->

      <!--sp only-->
      <div class="pc-none">
        <div class="flex-container item-center nowrap">
            <a href="<?php echo esc_url(home_url('/')); ?>">
                <img src="<?php echo esc_url(home_url()).'/wp/wp-content/uploads/logo.png'; ?>" class="header__logo" alt="ロゴ">
            </a>

            <div class="show-down-md header__hamburger">
                <div class="hamburger hamburger--slider" id="js__menu--btn">
                    <span class="hamburger-box">
                        <span class="hamburger-inner"></span>
                    </span>
                </div>
            </div>

            <div class="header__menu" id="js__menu">
                <ul class="flex-fluid menu__ul--main" id="js__menu--ul">
                    <li>
                        <a href="<?php echo esc_url(home_url('/about')); ?>"><span class="show-down-md"><i class="fas fa-angle-right"></i></span> <span class="font-b_sp">私たちについて</span></a>
                    </li>
                    <li class="menu__li--ex">
                        <span class="disabled menu__li--exSpan"><span class="font-b_sp">お悩み</span> <span class="show-up-lg"><i class="fas fa-angle-down" style="margin-left:2px"></i></span></span>
                        <ul class="menu__ul--sub">
                            <li>
                                <a href="<?php echo esc_url(home_url('/parts')); ?>">
                                    <span class="show-down-md"><i class="fas fa-angle-right"></i> </span>部位別のお悩み
                                </a>
                            </li>

                            <li>
                                <a href="<?php echo site_url(home_url('/').'pain_expert'); ?>" class="hover-w no-link">専門的なお悩み
                                </a>
                            </li>
                            <li class="header_small">
                              <a class="spfont-14" href="<?php echo esc_url(home_url('/herniated_disc')); ?>">
                                <span class="show-down-md"><i class="fas fa-angle-right"></i> </span>椎間板ヘルニア
                              </a>
                            </li>
                            <li class="header_small">
                              <a class="spfont-14" href="<?php echo esc_url(home_url('/spinal_canal_stenosis')); ?>">
                                <span class="show-down-md"><i class="fas fa-angle-right"></i> </span>脊柱管狭窄症
                              </a>
                            </li>
                            <li class="header_small">
                              <a class="spfont-14" href="<?php echo esc_url(home_url('/maternity_problems')); ?>">
                                <span class="show-down-md"><i class="fas fa-angle-right"></i> </span>産前産後のお悩み
                              </a>
                            </li>
                            <li class="header_small">
                              <a class="spfont-14" href="<?php echo esc_url(home_url('/sports_injuries')); ?>">
                                <span class="show-down-md"><i class="fas fa-angle-right"></i> </span>スポーツ障害のお悩み
                              </a>
                            </li>
                            <li class="header_small">
                              <a class="spfont-14" href="<?php echo esc_url(home_url('/deskworker_problems')); ?>">
                                <span class="show-down-md"><i class="fas fa-angle-right"></i> </span>デスクワーカーのお悩み
                              </a>
                            </li>
                            <li class="header_small">
                              <a class="spfont-14" href="<?php echo esc_url(home_url('/osteoarthritis')); ?>">
                                <span class="show-down-md"><i class="fas fa-angle-right"></i> </span>変形性膝関節・股関節症
                              </a>
                            </li>

                            <li>
                                <a href="<?php echo site_url(home_url('/').'pain_expert'); ?>" class="hover-w no-link">姿勢のお悩み
                                </a>
                            </li>
                            <li class="header_small">
                              <a class="spfont-14" href="<?php echo esc_url(home_url('/straight_neck')); ?>">
                                <span class="show-down-md"><i class="fas fa-angle-right"></i> </span>ストレートネック
                              </a>
                            </li>
                            <li class="header_small">
                              <a class="spfont-14" href="<?php echo esc_url(home_url('/round_back')); ?>">
                                <span class="show-down-md"><i class="fas fa-angle-right"></i> </span>猫背
                              </a>
                            </li>
                            <li class="header_small">
                              <a class="spfont-14" href="<?php echo esc_url(home_url('/scoliosis')); ?>">
                                <span class="show-down-md"><i class="fas fa-angle-right"></i> </span>側わん症
                              </a>
                            </li>
                            <li class="header_small">
                              <a class="spfont-14" href="<?php echo esc_url(home_url('/straight_back')); ?>">
                                <span class="show-down-md"><i class="fas fa-angle-right"></i> </span>ストレートバック
                              </a>
                            </li>


                        </ul>
                    </li>
                    <li class="menu__li--ex">
                        <span class="menu__li--exSpan"><span class="font-b_sp">施術・サービス</span> <span class="show-up-lg"><i class="fas fa-angle-down" style="margin-left:2px"></i></span></span>
                        <ul class="menu__ul--sub">
                            <li>
                                <a href="<?php echo esc_url(home_url('/').'chiropractic'); ?>">
                                    <span class="show-down-md"><i class="fas fa-angle-right"></i> </span>カイロプラクティック
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo esc_url(home_url('/').'cbp'); ?>">
                                    <span class="show-down-md"><i class="fas fa-angle-right"></i> </span>CBP®︎姿勢矯正
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo esc_url(home_url('/').'myofascial_release'); ?>">
                                    <span class="show-down-md"><i class="fas fa-angle-right"></i> </span>筋膜リリース
                                </a>
                            </li>
                            <li>
                                <a href="https://aapilates.jp/">
                                    <span class="show-down-md"><i class="fas fa-angle-right"></i> </span>ピラティス（専門サイトへ）
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="menu__li--ex">
                        <span class="menu__li--exSpan"><span class="font-b_sp">当院情報</span> <span class="show-up-lg"><i class="fas fa-angle-down"style="margin-left:2px"></i></span></span>
                        <ul class="menu__ul--sub">
                            <li>
                                <a href="<?php echo esc_url(home_url('/').'clinic-information#staff'); ?>"><span class="show-down-md"><i class="fas fa-angle-right"></i></span> スタッフ</a>
                            </li>
                            <li>
                                <a href="<?php echo esc_url(home_url('/').'clinic-information#price'); ?>"><span class="show-down-md"><i class="fas fa-angle-right"></i></span> 料金</a>
                            </li>
                            <li>
                                <a href="<?php echo esc_url(home_url('/').'clinic-information#faq'); ?>"><span class="show-down-md"><i class="fas fa-angle-right"></i></span> FAQ</a>
                            </li>
                            <li>
                                <a href="<?php echo esc_url(home_url('/').'clinic-information#access'); ?>"><span class="show-down-md"><i class="fas fa-angle-right"></i></span> アクセス</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="http://aachiro.tokyo/" class="header__en"><span class="show-down-md"><i class="fas fa-angle-right"></i></span> <span class="font-b_sp">ENGLISH</span></a>
                    </li>
                    <li>
                        <p class="header__contact"><a href="https://aachiro.jp/contact/">お問い合わせ</a></p>
                        <p class="header__contact--tel">
                            <a href="tel:0363124223">☎03-6312-4223</a>
                        </p>
                    </li>
                </ul>
            </div>
        </div>
      </div><!-- // sp only-->
    </header>
